css/emoji-mart.css

Some OS (Linux, Windows) still have ugly big scrollbars. Let’s remove horizontal scroll.
Before:
After:

Show only vertical scroll

---

css/emoji-mart.css

On our web site picker is looked like:
(Note about spaces under category icons)
It happens because some of webpage styles inherits to component. Here we have a problem because of inherited `line-height` (we set it to 1.4).
This fix override problem.
(I wait until all browsers will support `all: initial`, so we will be able to do inherit properties isolation better).

Isolate .emoji-mart-anchors from page line-height

---

README.md
package.json
scripts/build-data.js
src/components/category.js
src/components/emoji.js
src/components/picker.js

This allows the emoji sheet to be served locally instead of always hitting the cdn. Useful for electron apps.
Also changes the github commit for emoji-data (aka emoji-datasource) to the npm's package. This saves a ton of time spent trying to git clone that repo.

Allow a custom backgroundImageFn to be passed in

---

src/components/emoji.js

When use inside of an editor, it's useful to be able to pass children down to the Emoji component in order to be able to use the custom images and not break editing

Allow passing children to Emoji component

---

src/utils/store.js

In multi-user environment (for example, Electron app), it would be nice for users to have separate 'frequently used' emoji lists.
This commits adds `setNamespace({string} namespace)` function to store module, so developer can set it to appropriate value after new user has been signed in.

Allow custom namespace for store

---

src/utils/store.js

Many browsers may support localStorage, but disable access to it in certain situations. For example, Safari private browsing mode will raise an exception if you try to access localStorage from a third-party domain, resulting in unhandled errors like...
> QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.
The easiest way to handle this for optional features is to simply try-catch all access to localStorage.

wrap localStorage access in try-catch

---

src/utils/index.js

`||` has a higher precedence than conditional operator (`? ... :`). Fixed by surrounding with parentheses.

Fix issue with operator in skin tone logic

---

src/index.js

(Accidentally added other commits to the branch source of this PR. Re-issuing with a branch containing only these changes).
Hi -
Really digging EmojiMart. It dropped in easily and works great!
I needed to do a little customization of the categories. Rather than modify the library directly, I decided to replace the methods at runtime, which necessitated exposing Category from the library.
Cheers,
-Courtland

Category: export from index.js

---

src/webpack.config.js

We discovered an IE11 bug that would expand the height of SVGs. The solution was to not remove the height and width attributes from the SVG element.

Preserve height and width on svgs

---

src/components/category.js
src/components/picker.js
src/components/search.js
src/utils/emoji-index.js

We would like to add an custom filter to only display certain emojis based upon their unified value.  For Windows 7/IE 11, anything with skin tones, flags and zero width joiners look pretty bad (i.e. their fallback values), so we want to filter that out using emojisToShowFilter property that gets passed in.
1. Search shouldn't show emojis that are filtered out.
1. Categories shouldn't show up if everything from that category is filtered out.  (For our case, we want to filter out flags)
Signed-off-by: Thomas Osugi <tosugi@pivotal.io>

Add emojisToShow filter

---

src/components/picker.js

This patch fixes an issue in Internet Explorer where clicking the category after entering something in the search bar would result in no visible behavior.

Fix categories on IE11

---

src/components/picker.js

Change order of style merge, so the width can be overridden to for example '100%'.
Suggested change is because I need the picker to have a width of 100% of the parent.

allow style overrides from user

---

README.md
src/components/picker.js

Added `include` and `exclude` props to filter emoji categories

---

README.md
src/components/picker.js
src/components/search.js

Title explains it. Let me know if you'd rather use `el.focus()` or want me to change anything.

add prop to autofocus search input

---

package.json
src/components/anchors.js
src/components/category.js
src/components/emoji.js
src/components/picker.js
src/components/preview.js
src/components/search.js
src/components/skins.js

while using emoji-mart i noticed a persistent warning message in my console nagging me to stop using `React.propTypes`, and use the `prop-types` packages instead. That shouldn't be an issue for React 15+ when using this package any longer

update components from React.PropTypes to PropTypes package

---

README.md
css/emoji-mart.css

1. introduce npm install instructions. Can be inferred but if you're like me, the first you do when trying new tools is `command + f` npm install
2. `word-break` was set to an invalid parameter
3. Mismatched property value threw an error in my text editor, so i fixed it

Installation instructions & stylesheet corrections

---

README.md
src/components/preview.js

When no emoji is being hovered, the default preview is shown (currently `department_store`).
By setting the `emoji` argument to an empty string, this fallback can be disabled.
This means that something will only show when an emoji is hovered.
This means that when both `emoji` and `title` are set to empty strings, the footer area will be empty.

Allow preview emoji to be hidden.

---

src/components/picker.js

If the `recent` category is excluded, this PR ensures that the Picker respects this and does not write to local storage anyway.
Previously, recent usage would be written to storage even if the `recent` category was ignored.

Do not store recently used if 'recent' category is excluded.

---

README.md
scripts/build-data.js

Emoji-data provides the ascii representation of the emoji, available under `text`. The emoticons are in the `texts` field. 
From the README for the `texts` field: *Each ASCII emoji will only appear against a single emoji entry*. This guarantees that an emoticon will map to a single emoji. 
The current version uses the ascii representation when no emoticon is available for an emoji, which leads to invalid results when looking up an emoticon. For example, `:)` returns `:blush:` and `:slightly_smiling_face:` where there should only be a single match `:slightly_smiling_face:`
I kept the ascii representation in the data since it might be useful to render a text-only version of the emoji.

Text representation of emoji is different from emoticon

---

example/webpack.config.js
package.json
src/components/picker.js
src/webpack.config.js
yarn.lock

Including the width of the browser scrollbar in the total picker width resolves this issue.
Before:
After:

Fix shift when scrollbar is rendered

---

scripts/build-data.js

This addresses #96.
This works around current limitations/inconsistences in `emoji-data` and `emojilib` by matching between the two libraries on the emoji character itself, rather than relying on a perfect match between the two disparate "short name" fields.
See individual commit messages, especially for a927821, for extra info.
Demo of new functionality:

Search country flags using country names

---

.npmignore
karma.conf.js
package.json
src/webpack.config.js
yarn.lock

I love EmojiMart. But current library size is 110 KB (gzipped and minified). IT is too big (it is half or my app bundle size).
I want to help with size optimization. But every optimization must be started from profiling.
I added two tools:
* [size-limit](https://github.com/ai/size-limit) to prevent size regression. It will be run after test to check library size. MobX, JSS and Material UI use it too.
* [webpack-bundle-analyzer](https://github.com/th0r/webpack-bundle-analyzer) to see real content of package.
This tools always showed few ways for optimization

Add package size profiling tools

---

.babelrc
package.json
scripts/build-data.js
scripts/define.js
src/utils/emoji-index.js
yarn.lock

1. Fixed missed `EMOJI_DATASOURCE_VERSION` from previous “Webpack → Babel” PR.
2. `data/index.js` now use ES5 exports, so we don’t need Babel for it.
3. I removed unnecessary `util` import and reduce EmojiMart size above 100KB.
/cc @davojta @EtienneLem

Babel fixes

---

.gitignore
data/index.js
package.json
scripts/build-data.js
src/utils/emoji-index.js

@EtienneLem More than 10% compression!
1. Data was moved from `data/index.js` to `data/data.js`.
2. Many fields were removed from `data/data.js`.
3. Uncompress code was added to `data/index.js` to add all fields removed in step 2.
As result API is the same (`require('emoji-mart/data')` return the same object), but size is smaller!

Compress data

---

css/emoji-mart.css

This improves mobile scrolling, [especially on mobile Chrome/Android](https://stackoverflow.com/a/41026886/680742). It provides a hint to the browser to move the scrollable element to a layer on the GPU, which leads to visibly smoother scrolling in Chrome/Android.
Chrome also warns about this in the Dev Tools:
Here's a video showing the before and after (note some overall lag due to using Android `screenrecord` plus DevTools being attached; the "after" version is even smoother without those things): https://gfycat.com/DamagedDistinctHorsechestnutleafminer

Use will-change:transform for smoother mobile scrolling

---

.babelrc
.gitignore
package.json
scripts/build-data.js
src/polyfills/createClass.js
src/polyfills/extends.js
src/polyfills/inherits.js
src/polyfills/objectGetPrototypeOf.js
src/polyfills/possibleConstructorReturn.js
src/polyfills/stringFromCodePoint.js
src/utils/build-search.js

I can see this project is in active development, but I thought this PR may be useful to you, even just as a proof of concept.
In the [Mastodon](https://github.com/tootsuite/mastodon) project we are currently integrating `emoji-mart`, but we'd like to avoid the situation where we need to load the entire module (921kB) for all users. We use `emojiIndex` extensively, but the picker itself is only needed on-demand. So in principle, if `emoji-mart` were distributed as an ES module (with `"module"` declared in `package.json`), then we'd be able to do:
```js
import { emojiIndex } from 'emoji-picker'
```
...and [Webpack tree-shaking](https://webpack.js.org/guides/tree-shaking/) would take care of the rest.
I'm not sure if the current master is a good representation of what you intend to ship in …

Build as ES module as well as CommonJS

---

README.md
src/components/category.js
src/components/picker.js

Fix #129 - Since the only things the store is used for is the "recent emojis" functionality and skin modifier persistence, if you pass down recent emojis through props and showPreview=false, the store will never be hit.

Allow passing down a `recent` prop instead of localStorage

---

README.md
src/components/category.js
src/components/picker.js
src/utils/index.js

This affects both localStorage and `recent`-backed "frequently used" category. Those store emoji IDs. But what if an emoji is deleted? The whole picker crashes. This ensures that invalid IDs are ignored.

Feature filter invalid emojis

---

README.md

Without `size` `<Emoji />` doesn't render correctly.

add required props in <Emoji /> example

---

spec/picker-spec.js
src/components/picker.js

Providing the `emojisToShowFilter` function to the component was causing the following React warning:
> ERROR: 'Warning: Each child in an array or iterator should have a unique "key" prop.
> 
> Check the render method of `Anchors`. See https://fb.me/react-warning-keys for more information.
>     in span (created by Anchors)
>     in Anchors (created by Picker)
>     in div (created by Picker)
>     in div (created by Picker)
>     in Picker'
The cause was that the new category that's created with the filtered results didn't have its `id` value specified (only its `name` and `emojis` attributes).
This PR simply adds the `id` field back into the category. I've added an additional test to check for it as well.
Thanks for this great component!

Bug Fix: Ensure category ids are not dropped after emojisToShowFilter call

---

src/components/emoji.js

My use of the fallback mechanism just added is the same as was mentioned in the linked issue.
```
<Emoji
set={'messenger'}
emoji={'shrug'}
size={24}
fallback={(emoji) => {
return `:${emoji.short_names[0]}:`
}}
/>
```
In a case where the fallback is utilised, I'd prefer that styling wasn't applied.
Of course, feel free to close this pull request if there are other reasons that the font-size needs to be maintained!

Emoji fallback shouldn't apply styling #157

---

src/components/picker.js

I tried to use Picker component with include props.
```jsx
<Picker
include={["foods", "nature"]}
onClick={this._updateEmoji.bind(this)}
showPreview={false} />
```
But it seems that sort order is different depending on browsers. It is a result by Desktop Chrome ( Mobile device emulator mode ) and Mobile Chrome ( iPhone X ).
Desktop Chrome ( emulator mode ) | Mobile Chrome ( iPhone X )
---|---
v64.0.3282.140 | v64.0.3282.112
return ["foods", "nature"] | return ["nature", "foods"]
I think this document in MDN is related.
[Array.prototype.sort()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) , 
> If compareFunction(a, b) returns 0, leave a and b unchanged with respect to each other, but sorted with respect to all different elements.  Note: the …

fix Categories sort compareFunction return to -1 from 0 in Picker component

---

src/components/picker.js

👋 
**Encountered issue:**
We provide the picker with custom emojis based on different contexts, which means that in certain circumstances, the picker has custom emojis that will not be present at the next opening.
However, the `CUSTOM_CATEGORY` emojis array is built outside of the `Picker` class, and is kept in memory for all uses of the Picker, and therefore keeps any emojis its provided in memory, even when the Picker receives an empty `custom` prop in the future.
**Fix:**
Upon construction of the `Picker`, as we check if the `custom` prop has no length, I check if the `CUSTOM_CATEGORY` object contains emojis with a length, and reset it if so, to avoid contamination.

Custom Emojis as a changing prop

---

src/utils/emoji-index.js

👋 
**Problem & how to reproduce:**
File `emoji-index.js` has four global variables, that will mutate whenever you search an emoji with the search input:
```
var originalPool = {}
var index = {}
var emojisList = {}
var emoticonsList = {}
```
Considering you have Emoji Pickers in different places (different communities), where the custom emojis that are provided to those pickers vary, if the index nor the pool get "contaminated" with the custom emojis of one Picker, every other will contain them in their search results.
**Solution provided**
_The best approach would probably have been to re-factor those four global variables to bind them to the Emoji Picker instead of having them be globally instantiated. However, the `emoji-index.js` util exports emojis and emoticons, therefore in order to …

Clearing custom emojis from index and pool when necessary

---

README.md
docs/index.js
src/components/picker.js
stories/index.js

Add the ability to select the first emoji after a search with `enter`
I added a new props, `onSelect`,  to be notified when an emoji is selected, either with a click or `enter`. I'm not sure how much the mouse event is used so I didn't want to just rename `onClick` to `onSelect`. 
The next step would be to add keyboard navigation in the list of emojis

Select first emoji in list with `enter`

---

src/index.js

`./utils/emoji-index/nimble-emoji-index` has a default export, not a named export.

Correct NimbleEmojiIndex reexport

---

css/emoji-mart.css
docs/emoji-mart.css

Hi! This adds support for native emojis in IE11, previously rendered as black & white icons. Adjusting the font stack will also enable full support on Edge too, some emojis are broken too.
IE11 on Windows 10 using native emoji:
Same platform, but after applying the change, it should render native emojis properly:
I didn't test in in previous windows versions, I suspect it won't work if font is not available.
Emoji-mart is awesome, saved us a lot of time - thanks for contributing it to the world!

Added font stack to support native emojis in IE11/Edge

---

src/components/picker/nimble-picker.js

In fixing #211, I neglected to also ensure that non-square (52x52) sprite sheets also work in the preview bar. This PR corrects that oversight.

Fixes display of non-52x52 sprite sheets in the preview bar

---

src/components/category.js
src/components/picker/nimble-picker.js
src/components/preview.js

Those simple changes would allow importing Nimbleicker directly and avoid having all.json bundled when using apple.json or other emoji collections.

Import compoments directly to avoid components/picker/index.js and have smaller bundle

---

css/emoji-mart.css

fixes #255 
On Ubuntu, Firefox uses a built-in Twemoji font, whereas other browsers like Chrome and GNOME Web (aka Epiphany Browser) use the built-in-to-the-OS EmojiOne font. This change respects the Firefox style while also fixing the GNOME Web style.
GNOME Web before:
GNOME Web after:
"Android Emoji" is for older version of Android before Noto Color was built-in.

fix: fix native emoji on Linux

---

src/components/emoji/nimble-emoji.js

closes issue [#252 ](https://github.com/missive/emoji-mart/issues/252)
On Firefox and Safari, emojis were larger than their 24px container and were splitting into multiple rows causing formatting issues. Adding this css rule will force the emoji's to not break.

fix: forces emoji's not to break line

---

src/components/picker/nimble-picker.js

Fixed bug where selecting the first emoji search result with the ENTER key ignores skin-tone selection. This bug was due to the fact that the emojis in a `Category` are rendered as `NimbleEmoji`, where skin-tone data and other properties are populated via `getSanitizedData` (this data is not present in the `Category`'s emoji). Clicking an emoji therefore worked as expected since the click triggered the `NimbleEmoji`'s `handleClick` function which called `getSanitizedData`. Pressing the enter key, however, triggered the `NimblePicker`'s `handleKeyDown` function which simply returned the first emoji in `SEARCH_CATEGORY` (thus lacking the skin-tone data). Imported `getSanitizedData` from `utils` and called it in `handleKeyDown` to resolve the issue. Please let me know if you would like any …

Fixed bug where selecting the first emoji search result with the ENTER KEY ignores skin tone selection

---

.babelrc
README.md
package.json
src/components/anchors.js
src/components/category.js
src/components/emoji/emoji.js
src/components/emoji/nimble-emoji.js
src/components/not-found.js
src/components/picker/nimble-picker.js
src/components/picker/picker.js
src/components/preview.js
src/components/search.js
src/components/skins-dot.js
src/components/skins-emoji.js
src/components/skins.js
src/utils/shared-default-props.js
src/utils/shared-props.js
yarn.lock

fixes #257 
There were a few things required in order to actually remove `prop-types` from the build:
1. Split `shared-props.js` into `shared-props.js` and `shared-default-props.js`, because one needs to be removed and the other one doesn't.
2. Use the [`additionalLibraries`](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types#additionallibraries) option in `babel-plugin-transform-react-remove-prop-types` to catch `shared-props.js` in addition to `prop-types`
3. Update the babel transform.
4. Use `removeImport: true`.
5. Add comment annotations to help give the babel transform some hints about what to remove.
I can confirm that this fixes the issue by running:
```bash
egrep -r '(prop-types|shared-props)' dist dist-es
```
And I observe that `prop-types` is …

fix: allow prop-types to be removed in production

---

README.md

docs: add more explicit dev docs

---

package.json
src/components/picker/nimble-picker.js
src/components/preview.js

It is useful to be able to disable the mouseover emoji preview area but still have showSkinTones available. In particular, in order to be able to use the component on iOS without having to double-click every time it is necessary to disable much mouseover behavior such as this. (see https://css-tricks.com/annoying-mobile-double-tap-link-issue/)
Also, it is useful to have a "prepare" script in the package.json so that it is possible to clone emoji-mart directly from a git repo without extra steps.

Support case where showPreview is false but showSkinTones is true. Also add prepare script.

---

.babelrc
.gitignore
README.md
package.json

fixes #259
This adds `dist-modern` as proposed in that issue. It also adds some text to the `README` so that folks know how to use the "slim" build.

feat: add slim builds for modern browsers

---

package.json

It's probably a rude awakening for some people when they use `emoji-mart` and it complains that `prop-types` are missing. I checked our build output, and the only third-party libraries we require are `react` and `prop-types`, but `react` is already specified as a `peerDependency`.
I looked to see how other React component libraries do it, and it seems [react-virtualized uses a dependency, not a peerDependency, for prop-types](https://unpkg.com/react-virtualized@9.21.0/package.json). So it seems reasonable for us to do the same.

fix: add prop-types to dependencies

---

README.md
css/emoji-mart.css
src/components/picker/nimble-picker.js
src/components/search.js

Fixes the issues described in #221:
1. Adds a new `i18n.clear` value (default of "Clear") as the accessible label for the clear button
2. ~~To give the clear button a focus style, avoid making it disabled when the search is focused. Otherwise when you press <kbd>tab</kbd>, it doesn't change focus to the clear button. (Rather than disabling it, I made it so that if you somehow click the button while searching, it just does nothing.)~~ _ignore, I was wrong about this_
3. Tweak the styles on the clear button to give it more padding, so that the outline appears nicer-looking. As an added bonus, this improves the touch target size for the button, although for the best a11y, [it really should be at least 44x44 pixels](https://a11yproject.com/posts/large-touch-targets/) (right now it's 23x19). …

fix: improve search/clear a11y

---

README.md
css/emoji-mart.css
src/components/anchors.js
src/components/picker/nimble-picker.js

fixes #219
1. Changes the categories `<div>` into a `<nav>` (see [navigation role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role) for details).
2. Changes each category button into a true `<button>`. This makes it tabbable, and you can press the <kbd>space</kbd> button to press them.
3. Adds `aria-label` for each button, since the `title` is not sufficient for a11y
4. Adds an `aria-label` to the `<nav>` to help distinguish it from any other `<nav>`s that may be on the page. This requires a new `i18n` label ("Emoji categories" by default).
Here is a GIF of me pressing <kbd>tab</kbd> and <kbd>spacebar</kbd> to demonstrate: https://gfycat.com/agedwindycockatiel

fix: make categories into accessible nav buttons

---

README.md
src/components/picker/nimble-picker.js
src/components/skins-dot.js

fixes #220
I still think this solution leaves a lot to be desired, but this is the best I could do for now while maintaining the existing design. I believe we should probably separate out the button that expands the menu and the buttons inside the menu, but this is a start.
1. I made all `<span>`s into `role="button"`. (It was too difficult to make them true `<button>`s, but I would love a PR in the future to do that. ) :slightly_smiling_face: Because they aren't true buttons, we have to handle `tabindex` and keydown (enter/spacebar) ourselves.
2. I added `aria-haspopup` and `aria-expanded` to indicate when the menu button is opened.
3. I added a `<section>` with `aria-label` set to the `i18n.skintext` (default: 'Choose your default skin tone') so that it's easier to tell what this mass …

fix: makes skin tone picker more accessible

---

README.md
css/emoji-mart.css
src/components/category.js
src/components/emoji/nimble-emoji.js
src/components/picker/nimble-picker.js

fixes #218 
This isn't my ideal implementation, but it broadly fixes the issues in #218. It's a good start. :slightly_smiling_face:
1. Convert each clickable `<span>` into a `<button>` so that it's keyboard-accessible
2. Wrap each category list into a `<section>` with an `aria-label` corresponding to that section (should probably be a `<ul>`, but we can do that later)
3. Wrap the entire list of categories in a `<section>` with its own `aria-label`, currently defaulting to "List of emoji". This can be tweaked using the `i18n` object.
Potentially we could also include the shortcodes in the `aria-label` for each button; for now it's just the emoji itself.

fix: improve a11y of emoji list

---

src/components/category.js

fixes #254 
This is basically the same fix as https://github.com/missive/emoji-mart/pull/268. I'm not sure what changed (or if something did), but based on my manual testing of the storybook with preact (https://github.com/nolanlawson/emoji-mart/commit/7bde2642b398c3b8fcc5aca45117bf0350cc19fc), this fixes preact compatibility. Everything seems to work correctly &ndash; searching, updating categories, etc.

fix: fix preact compatibility

---

src/components/search.js
src/utils/index.js

Responsiveness while typing in the search bar can be sluggish, because we are updating on every `change` event. With this PR, we throttle the change listener based on `requestIdleCallback`/`setTimeout` to avoid sluggishness.
The easiest way to reproduce this is to put the Chrome Dev Tools on 6x slowdown, and then type very fast. Especially when deleting the first letter, you can feel the delay.

perf: throttle keyboard input to improve responsiveness

---

src/components/not-found.js

While playing with the storybook, I noticed a warning:
```
Warning: Failed prop type: The prop `notFoundString` is marked as required in `NotFound`, but its value is `undefined`.
in NotFound (created by Category)
in Category (created by NimblePicker)
in div (created by NimblePicker)
in div (created by NimblePicker)
in NimblePicker (created by Picker)
in Picker
in WrapStory
```
This prop seems to be entirely unused, since this component actually uses `i18n.notfound` instead. I also can't find any documentation or any other references to it. It seems safe to remove.

fix: remove unused notFoundString prop

---

src/components/picker/nimble-picker.js

fixes #201 
Steps to reproduce:
1. Open the storybook
2. Type some text that results in "not found"
3. Press enter
4. Check the dev console for the error
The error is:
```
Uncaught TypeError: Cannot read property 'id' of undefined
at getData (index.js:99)
at getSanitizedData (index.js:73)
at NimblePicker.handleKeyDown (nimble-picker.js:476)
at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
at Object.invokeGuardedCallback (react-dom.development.js:1195)
at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:1209)
at executeDispatch (react-dom.development.js:1432)
at Object.executeDispatchesInOrder (react-dom.development.js:1454)
at executeDispatchesAndRelease …
```

fix: fix emoji.id undefined error

---

src/components/search.js

In some cases (notably with Preact it seems), the `<input type="search">` value may be prepopulated (due to cached DOM nodes being re-hydrated, I suppose). In those cases, you can cause a bug if you do e.g.:
1. Type "horse" into the search
2. Press enter to choose the :horse: emoji
3. Reopen the picker (can't be reproduced in the storybook, but can be reproduced in [Pinafore](http://github.com/nolanlawson/pinafore/))
4. The search input is prepopulated, but the search results are empty
This fixes that, by performing a search if the input happens to contain any text.

fix: fix search input when value is prepopulated

---

src/components/skins-dot.js

This is something I missed in #283. Apparently React uses `tabIndex`, not `tabindex`.

fix: use tabIndex, not tabindex

---

README.md
src/components/picker/nimble-picker.js
src/components/preview.js
src/components/search.js

Makes some progress on #294 
- Remove `emojilist` i18n text and region, just let each category have its own region
- Add a region for the entire emoji picker, same as the title shown in the preview bar
- Add a region for the search, using the same label as the placeholder for the input
- Make the preview aria-hidden since it is decorative
This may still be better with headers rather than regions, but since we can't know how emoji-mart will be hosted on a page, we can't know whether to use h1 vs h2, etc. So regions seem safer to me, but admittedly I'm not an expert.

fix: improve accessible page structure

---

src/components/skins-dot.js

I don't think this is a full fix for #294 but it's a bit better than before. When the picker is not expanded, it's a popup button, then when you click it it becomes a toggle button within a menu item within a menu of similar buttons.
I tested this in NVDA and VoiceOver, and it works much better in NVDA than VoiceOver (VoiceOver doesn't seem to notice the toggle state for the buttons, nor the menu). But it's usable in either one.

fix: improve a11y of skin tone picker

---

css/emoji-mart.css
src/components/category.js
src/components/emoji/nimble-emoji.js

Fixes another a11y issue from #294.
Unfortunately I couldn't find a way to make these into lists/listitems without actually adding new `<li>`/`<ul>` elements. So this is potentially a performance hit by adding one more DOM node per list item. But I think it's worth it to make these lists more accessible.

fix: make each emoji category into a list

---

src/utils/index.js

It occurred to me that I was making this requestIdleCallback more complex than it needed to be. This simplifies it, and also avoids some unnecessary cancelIdleCallback calls.

fix: improve requestIdleCallback usage

---

package.json

This is something I missed when I added `dist-modern`

chore: `yarn clean` should remove dist-modern

---

README.md

Fixes #305
I wrote a small sample app showing how to use emoji-mart as a vanilla custom element. Hopefully it will help someone else trying to use emoji-mart outside React: https://github.com/nolanlawson/emoji-mart-outside-react

docs: add example of how to use outside React

---

src/utils/index.js

https://github.com/missive/emoji-mart/blob/d739f27714c4b1e28f3d92f654a5ba83933c2816/src/components/emoji/nimble-emoji.js#L118
throws `TypeError: Cannot read property '0' of undefined`. (It makes https://github.com/tootsuite/mastodon/issues/10315 )
This is one of way to resolve issue, but it may not a good way.

keep short_names on sanitize

---

src/utils/emoji-index/__tests__/emoji-index.test.js
src/utils/index.js

Based on #308 I am just going to assume that we always need to return `short_names` here. Admittedly, though, I haven't managed to write a Jest test to actually reproduce #308, nor can I prove that this is actually currently causing a bug. But it seems harmless to return `short_names` here.

fix: consistently return short_names from sanitize

---

README.md

I accidentally messed up the Travis config a bit. It looks like someone with admin access to the https://github.com/missive org will have to enable Travis CI, because I can only enable it for `nolanlawson/emoji-mart`.

docs: fix travis CI badge

---

src/components/__tests__/__snapshots__/not-found.test.js.snap
src/components/emoji/nimble-emoji.js
src/utils/shared-default-props.js

Fixes #309
- No more default `onClick` handler (undefined `props.onClick` was already handled)
- When `onClick` is defined, use `<Button>` with `type="button"` (see https://github.com/missive/emoji-mart/issues/309#issuecomment-476087144)

fix: use span for non-clickable emojis

---

package.json
src/components/__tests__/skins-dot.js
src/components/skins.js
yarn.lock

Trying to improve the test infrastructure of emoji-mart. I want to test actual behavior, but ideally without launching an actual browser (or JSDom). Seems Enzyme is one of the most popular ways to do this with Jest. So this adds a simple test for the skintone picker.

test: add basic skins test

---

src/utils/emoji-index/nimble-emoji-index.js

This is important for reliable tests, e.g. if you are snapshotting views
and comparing to reference images.
Pair with https://github.com/thinkproductivity/emoji-mart-native/pull/62

Deterministic sorting of search results.

---

src/components/category.js

fixes #327
Probably the `id` in the index itself should be guaranteed to be unique as well, but this at least fixes the React warning.

fix: ensure unique keys for React list

---

src/components/picker/nimble-picker.js

The `handled` variable should only be set when we actually call the `handleEmojiSelect` function, otherwise it overrides default button behaviour of being selectable by the enter key. 
This causes an issue for accessible keyboard navigation: https://webaim.org/techniques/keyboard/
Fixes #353

Fix: Allowing emoji selection on enter

---

src/components/picker/nimble-picker.js

`componentWillReceiveProps` will be removed from React 17.x. So, I use `getDerivedStateFromProps` instead of it. 
This pull request solves issue #356.

Use getDerivedStateFromProps instead of componentWillReceiveProps

---

README.md

Looks like the `With custom data` section of `Headless search` got pushed down by the `Get emoji data from Native` stuff.

Move `With custom data` to correct position

---

src/utils/store.js

We were previously using an [Angular port](https://github.com/TypeCtrl/ngx-emoji-mart) of emoji-mart, then we migrated our application to React, and began using the original emoji-mart.  That port used the `emoji-mart.last` localstorage item slightly differently, by not JSON-encoding it. After the migration, our app would crash while rendering emoji-mart, as it attempted to parse the stale value from our users' localstorage.
This PR changes the store's behaviour to discard invalid JSON values instead of raising an error through `JSON.parse`. That way, if those values ever become corrupt or otherwise invalid for some reason, things like recent emoji just get forgotten, instead of the app inexplicably crashing.

fix: gracefully ignore bad JSON in localstorage

---

src/components/picker/nimble-picker.js
src/utils/index.js
src/utils/store.js

Fixes #393 
This removes `core-js` from our output bundle... for now. In the future, we need to come up with a better system for ensuring that Babel doesn't include `core-js` in our bundle.

fix: remove core-js dependency

---

src/utils/emoji-index/__tests__/emoji-index.test.js

We expose the `emojis` and `emoticons` objects from `emoji-index.js` but they weren't tested anywhere as far as I can tell. This adds a test for them.

test: add test for emoji-index.js

---

.travis.yml
package.json

We have this test (to keep the size under 80kB), but it's not currently running in CI. This fixes that.

test: test bundle size in CI

---

src/utils/index.js
src/utils/store.js

I can confirm that, once #397 is merged, then we no longer need this hack (which avoided `core-js`/`@babel/runtime` from including a large polyfill). That makes sense, since JSON has been available [since IE8](https://caniuse.com/#feat=json).

refactor: remove _JSON

---

src/components/picker/nimble-picker.js
src/utils/shared-default-props.js
src/utils/shared-props.js
stories/index.js

This is in reference to issue #366.
I added:
- a bool value `disableFrequentEmojiSort` that defaults to false 
- functionality in storybook so we can all see it in action
I'm very open to any feedback anyone has so please let me know if I missed anything...its been known to happen 😉😂
Thank you guys!

enhancement: functionality to disable the frequent emoji sorting

---

src/components/search.js

not really sure how to reproduce, but apparently one of my users managed to time their search perfectly (probably due to the throttle?).
this should prevent that.

safely access this.input.value

---

src/components/anchors.js

The aria-label and title weren't showing up for the Custom button.

Fix aria-label and title for custom categories

---

packages/emoji-mart/package.json

Fixes #613 
Fixes #602 
Fixes #582 
Added `browserslist` as `defaults` to package.json of `emoji-mart` package. This makes sure that the code is transpiled to support wider range of browsers.
Quoting from [parcel](https://parceljs.org/getting-started/webapp/#declaring-browser-targets):
>  By default Parcel does not perform any code transpilation. This means that if you write your code using modern language features, that’s what Parcel will output. You can declare your app’s supported browsers using the browserslist field. When this field is declared, Parcel will transpile your code accordingly to ensure compatibility with your supported browsers.
Having a `browserslist` key in package.json has the additional benefit of specifying which all browsers the current version of the package …

Added 'defaults' browserslist to emoji-mart package.json

---

packages/emoji-mart/src/config.js

When I add a custom emoji category, I cannot indicate a custom id, so a default one is used what is a bit uncomfortable when I have to fill the categories array.
Current case:
```
init({
...,
custom: [{ name: "Basic", emojis: [ … ] }],
categories: ["custom_1"]
})
```
After this change:
```
init({
...,
custom: [{ id: "basic", name: "Basic", emojis: [ … ] }],
categories: ["basic"]
})
```

Allow to use an id for custom categories

---

packages/emoji-mart/src/components/Picker/Picker.js
packages/emoji-mart/src/components/Picker/PickerStyles.scss

Users can navigate emojis using the arrow keys on their keyboards. Unfortunately, this behavior does not announce to screen reader users what the currently selected emoji is.
Add an [ARIA live region](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions) only visible to screen readers (hidden from the UI) that announces the currently selected emoji.
This can be tested using a screen reader like VoiceOver on the Mac 👇

Make selected emoji accessible to screen readers

---

packages/emoji-mart/src/components/HTMLElement/HTMLElement.ts

Not supported by older versions of Webpack
Fixes #727

Remove optional chaining

---

packages/emoji-mart/src/components/Picker/Picker.tsx

Could be used, for example, to detect if meta key is pressed and not automatically close the picker if the default behavior would be for the picker to be closed upon selecting an emoji.

Send native event to `onEmojiSelect`

---

README.md
packages/emoji-mart-website/example-dynamic-width.html
packages/emoji-mart-website/examples.html
packages/emoji-mart/src/components/Picker/Picker.tsx
packages/emoji-mart/src/components/Picker/PickerProps.ts
packages/emoji-mart/src/components/Picker/PickerStyles.scss

Dynamic width

---

packages/emoji-mart-data/index.d.ts
packages/emoji-mart-data/package.json
packages/emoji-mart-react/package.json
packages/emoji-mart-react/react.tsx

@emoji-mart/react and @emoji-mart/data TS types

---

packages/emoji-mart/src/components/Picker/Picker.tsx

This allows the callback to filter target elements.
Given:
- A custom trigger callback that opens the picker popup.
- And then the `onClickOutside` callback set to close the popup on outside clicks.
Issue: Without excluding the trigger element target in the `onClickOutside` callback, the popup is opened by the first callback and then closed instantly by the second callback, as it is registered as an outside click.

Relay event arg to `onClickOutside` callback

---

README.md
packages/emoji-mart-website/index.html
packages/emoji-mart/README.md
packages/emoji-mart/src/components/Picker/PickerProps.ts
packages/emoji-mart/src/config.ts

Add `exceptEmojis` props to excepting some custom emojis that don't wants showing to emojis list
for example:
```js
exceptEmojis: ['hankey'],
```

Add `exceptEmojis` props

---

packages/emoji-mart/src/config.ts

```ts
import data from "@emoji-mart/data";
import { init } from "emoji-mart";
init({ data });
```
Before: `TypeError: undefined is not an object (evaluating 'props.exceptEmojis.includes')`
After: ✅

Make `exceptEmojis` optional when calling `init`
