missive/emoji-mart

src/components/emoji.js
Hi, I ran into an issue with the Emoji component where the component would not update if the "emoji" prop changed, I added a rule to shouldComponentUpdate which resolves the issue.
=> Add emoji prop change check to Emoji component

karma.conf.js, package.json, src/components/pickerSpec.js, src/utils/emoji-indexSpec.js, src/webpack.config.js
I wanted to add jasmine + karma runner unit testing framework to help give us better confidence at future changes will not break existing features.
Currently tests for emojisToShowFilter are commented out pending acceptance of that pull request.
Let me know how you feel about this!
Thanks,
-Tom
=> Add karma/jasmine + tests for emoji-index and picker

scripts/build-data.js
https://github.com/missive/emoji-mart/issues/48
This seemed like the only file reduction change that wouldn't reduce additional complexity and brittleness, but take a look at `:master` and see if there is anything else you think would be worth including here.
=> Data file size reduction: strip quotes around keys

src/utils/emoji-index.js
`data.emojis` doesn't include custom emojis and is passing `undefined` to `emojisToShowFilter`
=> Fix search with custom data and filter

README.md
It took me a while for to find the reason why the UI is messy.
Thanks for the awesome package!
=> doc: add css in readme

src/components/anchors.js
Addresses #219. 
With the addition the categories should be able to tabbed through keyboard
=> fix(a11y): ability to tab through different categories

README.md, docs/bundle.js, docs/index.js, src/components/emoji/nimble-emoji.js, src/index.js
Adds support for spritesheets as asked in https://github.com/missive/emoji-mart/issues/247. I opted out of using 'position: [row, column]' because the variables sheet_(x|y), size, and sheet(Columns|Rows) are already implemented. The main thing added is spriteUrl to the custom emoji data.
=> Adds Spritesheets for Custom Emojis

.babelrc, src/polyfills/classCallCheck.js, src/polyfills/keys.js
=> fix: fix babel-runtime not found

stories/index.js
GitHub changed the URL for these icons.
=> chore: fix custom emoji URLs in storybook

src/components/category.js, src/components/skins-dot.js
At some point I must have accidentally messed up the prettier formatting. Automated CI tests would catch this.
=> chore: fix prettier linting

.travis.yml, README.md, package.json, src/components/category.js, src/components/search.js, src/polyfills/stringFromCodePoint.js, yarn.lock
- Adds a Travis CI test to run jest and prettier
- Upgrades prettier to the latest version
- Fixes some prettier errors due to the upgrade
=> chore: add Travis CI tests

src/components/category.js, src/components/picker/__tests__/nimble-picker.test.js, src/components/picker/nimble-picker.js
Based on https://github.com/missive/emoji-mart/pull/317#issuecomment-475845727
=> test: add test for short_names in custom emoji

src/components/anchors.js
without this it will submit the form if you are within a redux form with react not sure about other libraries but the button doesn't seem to need to not have this type attribute
=> Added `type={"button"}` to anchors.js

README.md
This prevents unnecessary work and prevents some translation errors that can easily occur, otherwise. (e.g. it's not that easy to translate the skin tones correctly)
E.g. I've also written a guide for my translators to help them to find that data in there: https://github.com/rugk/awesome-emoji-picker/blob/master/CONTRIBUTING.md#translating-emoji-terms-categories-skin-names-etc
Related to: https://github.com/missive/emoji-mart/issues/303
=> Add tip for l10n to use CLDR

README.md
=> docs: document how to remove the footer

src/components/emoji/nimble-emoji.js
=> Ensure emoji backgrounds do not tile

README.md, src/components/anchors.js, src/components/category.js, src/components/picker/__tests__/nimble-picker.test.js, src/components/picker/nimble-picker.js, src/utils/index.js, stories/index.js
=> Add support for more than one custom category

src/utils/index.js, src/utils/store.js
Noticed this in #385, not sure what purpose it serves and it's inconsistently applied, so we should be able to remove it.
=> fix: remove _JSON

css/emoji-mart.css
Fixes https://github.com/missive/emoji-mart/issues/409
=> Fix x overflow on Windows with native emojis

packages/emoji-mart-data/i18n/zh.json
This is a Chinese translations.
I use sense-for-sense translation as much as possible to ensure the use experience of Chinese users 😀
=> Add Chinese translations

packages/emoji-mart-data/i18n/nl.json, packages/emoji-mart-website/index.html, packages/emoji-mart/src/config.js
=> Added Dutch (NL) translation

packages/emoji-mart-data/i18n/tr.json, packages/emoji-mart-website/index.html, packages/emoji-mart/src/components/Picker/PickerProps.ts
=> ADD: Turkish Language

packages/emoji-mart/src/components/Emoji/Emoji.tsx
=> Remove restrictive custom emoji styling

README.md, packages/emoji-mart-data/i18n/kr.json, packages/emoji-mart-website/index.html, packages/emoji-mart/src/components/Picker/PickerProps.ts
=> ADD: Korean Language 

packages/emoji-mart/src/components/Picker/Picker.tsx
Regression since 03960bd
Fixes #762
=> Fix picker width changing when hovering emojis

packages/emoji-mart/src/components/Picker/PickerStyles.scss
There were meant to be set on :host to be configurable
=> Fix preview font-size variables
